// Generated by `create-noy-db`.
//
// `defineNoydbStore` is auto-imported by @noy-db/nuxt. The store wires
// a Pinia store to a noy-db compartment + collection. Encryption,
// keyring management, and adapter wiring are invisible to components.

export interface Invoice {
  id: string
  client: string
  amount: number
  status: 'draft' | 'open' | 'paid' | 'overdue'
  dueDate: string
}

export const useInvoices = defineNoydbStore<Invoice>('invoices', {
  compartment: 'demo-co',
})

/**
 * Default seed records rendered into the store on first mount (see
 * `app/pages/invoices.vue`). An empty array means the page starts empty.
 */
export const DEFAULT_INVOICES: Invoice[] = {{SEED_INVOICES}}
