// Generated by `create-noy-db`.
//
// The `noydb:` key is fully typed via @noy-db/in-nuxt's module augmentation
// of @nuxt/schema. Hover any field for documentation.

export default defineNuxtConfig({
  compatibilityDate: '2026-04-01',

  modules: [
    '@pinia/nuxt',
    '@noy-db/in-nuxt',
  ],

  noydb: {
    adapter: '{{ADAPTER}}',
    pinia: true,
    devtools: {{DEVTOOLS}},
  },

  devtools: {
    enabled: process.env['NODE_ENV'] !== 'production',
  },

  telemetry: false,

  typescript: {
    strict: true,
    typeCheck: false,
  },
})
